name: 'Setup Environment'
description: 'Set up the environment for deployment.'
inputs:
  mongodb_username:
    description: 'MongoDB Username'
    required: true
  mongodb_password:
    description: 'MongoDB Password'
    required: true
  app_env:
    description: 'Application Environment'
    required: true
  app_owner:
    description: 'Application Owner'
    required: true
  app_version:
    description: 'Application Version'
    required: true
  port:
    description: 'Application Port'
    required: true
  branch_to_deploy:
    description: 'Branch to checkout before performing terraform commands'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Display Custom Linux Environment
      run: |
        echo "APP_ENV: ${{ inputs.app_env }}"
        echo "APP_OWNER: ${{ inputs.app_owner }}"
        echo "APP_VERSION: ${{ inputs.app_version }}"
    
    - name: Get Code
      uses: actions/checkout@v4
      with:
        clean: false
        fetch-depth: 0
        ref: ${{ inputs.branch_to_deploy }}
    
    - name: Cache Dependencies
      uses: actions/cache@v4
      with:
        path: ~/.npm
        key: npm-deps-${{ hashFiles('**/package-lock.json') }}
    
    - name: Install Dependencies
      run: npm ci
    
    - name: Run Server
      run: npm start & npx wait-on http://127.0.0.1:${{ inputs.port }}
    
    - name: Run Tests
      run: npm test
    
    - name: Output Information
      run: |
        echo "MONGODB_USERNAME: ${{ inputs.mongodb_username }}"
