name: Multi-env-deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to deploy'
        required: true
        default: 'poc'
        options:
          - prod
          - test
          - poc
      branch_to_deploy:
        description: 'Branch to checkout before performing terraform commands'
        type: string
        required: true

env:
  MONGODB_DB_NAME: gha-demo
  PORT: '8080'

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          mongodb_username: ${{ secrets.MONGODB_USERNAME }}
          mongodb_password: ${{ secrets.MONGODB_PASSWORD }}
          app_env: ${{ vars.APP_ENV }}
          app_owner: ${{ vars.APP_OWNER }}
          app_version: ${{ vars.APP_VERSION }}
          port: ${{ env.PORT }}
          branch_to_deploy: ${{ github.event.inputs.branch_to_deploy }}

  deploy:
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Environment
        uses: ./.github/actions/deploy
        with:
          mongodb_username: ${{ secrets.MONGODB_USERNAME }}
          mongodb_db_name: ${{ env.MONGODB_DB_NAME }}
          environment: ${{ github.event.inputs.environment }}
